// /src/config/usStates.ts  includes DC and territories such as, Puerto Rico and Guam

export const US_STATES = [
    { label: "Alabama", value: "Alabama", slug: "alabama" },
    { label: "Alaska", value: "Alaska", slug: "alaska" },
    { label: "American Samoa", value: "American Samoa", slug: "american-samoa" },
    { label: "Arizona", value: "Arizona", slug: "arizona" },
    { label: "Arkansas", value: "Arkansas", slug: "arkansas" },
    { label: "California", value: "California", slug: "california" },
    { label: "Colorado", value: "Colorado", slug: "colorado" },
    { label: "Connecticut", value: "Connecticut", slug: "connecticut" },
    { label: "Delaware", value: "Delaware", slug: "delaware" },
    { label: "District of Columbia", value: "District of Columbia", slug: "district-of-columbia" },
    { label: "Florida", value: "Florida", slug: "florida" },
    { label: "Georgia", value: "Georgia", slug: "georgia" },
    { label: "Guam", value: "Guam", slug: "guam" },
    { label: "Hawaii", value: "Hawaii", slug: "hawaii" },
    { label: "Idaho", value: "Idaho", slug: "idaho" },
    { label: "Illinois", value: "Illinois", slug: "illinois" },
    { label: "Indiana", value: "Indiana", slug: "indiana" },
    { label: "Iowa", value: "Iowa", slug: "iowa" },
    { label: "Kansas", value: "Kansas", slug: "kansas" },
    { label: "Kentucky", value: "Kentucky", slug: "kentucky" },
    { label: "Louisiana", value: "Louisiana", slug: "louisiana" },
    { label: "Maine", value: "Maine", slug: "maine" },
    { label: "Maryland", value: "Maryland", slug: "maryland" },
    { label: "Massachusetts", value: "Massachusetts", slug: "massachusetts" },
    { label: "Michigan", value: "Michigan", slug: "michigan" },
    { label: "Minnesota", value: "Minnesota", slug: "minnesota" },
    { label: "Mississippi", value: "Mississippi", slug: "mississippi" },
    { label: "Missouri", value: "Missouri", slug: "missouri" },
    { label: "Montana", value: "Montana", slug: "montana" },
    { label: "Nebraska", value: "Nebraska", slug: "nebraska" },
    { label: "Nevada", value: "Nevada", slug: "nevada" },
    { label: "New Hampshire", value: "New Hampshire", slug: "new-hampshire" },
    { label: "New Jersey", value: "New Jersey", slug: "new-jersey" },
    { label: "New Mexico", value: "New Mexico", slug: "new-mexico" },
    { label: "New York", value: "New York", slug: "new-york" },
    { label: "North Carolina", value: "North Carolina", slug: "north-carolina" },
    { label: "North Dakota", value: "North Dakota", slug: "north-dakota" },
    { label: "Northern Mariana Islands", value: "Northern Mariana Islands", slug: "northern-mariana-islands" },
    { label: "Ohio", value: "Ohio", slug: "ohio" },
    { label: "Oklahoma", value: "Oklahoma", slug: "oklahoma" },
    { label: "Oregon", value: "Oregon", slug: "oregon" },
    { label: "Pennsylvania", value: "Pennsylvania", slug: "pennsylvania" },
    { label: "Puerto Rico", value: "Puerto Rico", slug: "puerto-rico" },
    { label: "Rhode Island", value: "Rhode Island", slug: "rhode-island" },
    { label: "South Carolina", value: "South Carolina", slug: "south-carolina" },
    { label: "South Dakota", value: "South Dakota", slug: "south-dakota" },
    { label: "Tennessee", value: "Tennessee", slug: "tennessee" },
    { label: "Texas", value: "Texas", slug: "texas" },
    { label: "U.S. Virgin Islands", value: "U.S. Virgin Islands", slug: "us-virgin-islands" },
    { label: "Utah", value: "Utah", slug: "utah" },
    { label: "Vermont", value: "Vermont", slug: "vermont" },
    { label: "Virginia", value: "Virginia", slug: "virginia" },
    { label: "Washington", value: "Washington", slug: "washington" },
    { label: "West Virginia", value: "West Virginia", slug: "west-virginia" },
    { label: "Wisconsin", value: "Wisconsin", slug: "wisconsin" },
    { label: "Wyoming", value: "Wyoming", slug: "wyoming" },
    { label: "Other", value: "Other", slug: "other" },
    { label: "Not Applicable", value: "Not Applicable", slug: "not-applicable" },
  ];
  